linters-settings:
    dupl:
        threshold: 100
    funlen:
        lines: 100
        statements: 50
    goconst:
        min-len: 2
        min-occurrences: 2
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - dupImport # https://github.com/go-critic/go-critic/issues/845
            - ifElseChain
            - octalLiteral
            - whyNoLint
            - wrapperFunc
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: mst
    golint:
        min-confidence: 0
    gomnd:
        settings:
            mnd:
                checks: argument,case,condition,return # don't include the "operation" and "assign"
    govet:
        check-shadowing: true
    lll:
        line-length: 140
    maligned:
        suggest-new: true
    misspell:
        locale: US
  
linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - funlen
        - gochecknoinits
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - golint
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - interfacer
        - lll
        - misspell
        - nakedret
        - rowserrcheck
        - scopelint
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace

    # don't enable:
    # - gochecknoglobals
    # - gocognit
    # - godox
    # - maligned
    # - prealloc

issues:
    # Excluding configuration per-path, per-linter, per-text and per-source
    exclude-rules:
        - path: _test\.go
          linters:
            - gomnd

run:
    skip-dirs:
        - test/

service:
    golangci-lint-version: 1.24.x # use the fixed version to not introduce new linters unexpectedly